# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'selfieTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  # Pods for selfieTest

  target 'selfieTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.4'
  end

  target 'selfieTestUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.4'
  end

end
